name: functional-objectstorage
on:
  pull_request:
    paths:
      - '*.go'
      - 'go.mod'
      - 'go.sum'
      - 'pagination/**'
      - 'openstack/*'
      - '**objectstorage**'
  schedule:
    - cron: '0 0 */3 * *'
jobs:
  functional-objectstorage:
    strategy:
      fail-fast: false
      matrix:
        name: ["master"]
        openstack_version: ["master"]
        ubuntu_version: ["22.04"]
        include:
          - name: "bobcat"
            openstack_version: "stable/2023.2"
            ubuntu_version: "22.04"
          - name: "antelope"
            openstack_version: "stable/2023.1"
            ubuntu_version: "22.04"
          - name: "zed"
            openstack_version: "stable/zed"
            ubuntu_version: "20.04"
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: Deploy OpenStack ${{ matrix.name }} with Swift and run objectstorage acceptance tests
    steps:
      - name: Checkout Gophercloud
        uses: actions/checkout@v4
      - name: Deploy devstack
        uses: EmilienM/devstack-action@e82a9cbead099cba72f99537e82a360c3e319c69
        with:
          branch: ${{ matrix.openstack_version }}
          conf_overrides: |
            SWIFT_ENABLE_TEMPURLS=True
            SWIFT_TEMPURL_KEY=secretkey
            [[post-config|\$SWIFT_CONFIG_PROXY_SERVER]]
            [filter:versioned_writes]
            allow_object_versioning = true
          enabled_services: 's-account,s-container,s-object,s-proxy'
      - name: Checkout go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
      - name: Run Gophercloud acceptance tests
        run: ./script/acceptancetest
        env:
          DEVSTACK_PATH: ${{ github.workspace }}/devstack
          ACCEPTANCE_TESTS_FILTER: '^.*objectstorage.*$'
          OS_BRANCH: ${{ matrix.openstack_version }}
      - name: Generate logs on failure
        run: ./script/collectlogs
        if: failure()
      - name: Upload logs artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: functional-objectstorage-${{ matrix.name }}
          path: /tmp/devstack-logs/*
